### ISSUE TITLE
OpenOCD needs 666 permission to access device?

### ISSUE THREAD

**Issue by rohitk-singh** [timvideos/litex-buildenv-udev#2]
@mithro With current rules, OpenOCD is not able to access the device for programming. I needed to do this to make it work -> https://github.com/timvideos/litex-buildenv-udev/commit/806c2a08e6fb6251f3cb8bf746ee535e70a41dbc

Is it correct workaround? Or should I add device-specific match-filter there like this: `ENV{ID_HDMI2USBDEV_BOARD}=="mimas_a7"` ?

**Comment by mithro** [comment]
Are you in group video?

**Comment by rohitk-singh** [comment]
Oh, that's why! I wasn't in the video group. After adding myself to the video group, now OpenOCD programs fine with original permissions. Thanks!

**Comment by mithro** [comment]
I wonder if there is a better group for HDMI2USB_DEV boards (rather than full HDMI2USB boards?)

**Comment by rohitk-singh** [comment]
dialout, tty? I'm not sure. This could be a mistake any person who is getting started with Litex-buildenv or HDMI2USB can easily make.
